### ISSUE TITLE
evaluateTransaction dropping connection on sanchonet

### ISSUE THREAD

**Issue by klarkc** [CardanoSolutions/ogmios#363]
### What Git revision / release tag are you using?

v6.0.2

### Do you use any client SDK? If yes, which one?

cardano-transaction-lib

### Describe what the problem is?

I'm attempting to evaluate this transaction:

```json
{"params":{"transaction":{"cbor":"84a4008182582055ed5376ddaafcc1d498d96d7d45ebda05a4c63c3f9e0e99a345df0218db8cb103018283583910793f8c8cffba081b2a56462fc219cc8fe652d6a338b62c7b134876e7899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e1a001e84805820923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec82583900a838a4e1280f3bf8e1462f7a9d728b3e277427cd08d0512594603ccd899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e1a4a4fe53002000f00a2049fd87980ff0580f5f6"},"additionalUtxo":[]},"method":"evaluateTransaction","jsonrpc":"2.0","id":"evaluateTransaction-ls2ebvv3"}
```

The connection is dropping without any additional information on the Ogmios side. Cardano-transaction-lib handles the connection drop by retrying a new connection with payload resubmission. Thus, it becomes an endless loop.

### What should be the expected behavior?

I'm expecting any kind of error (if the CBOR is being incorrectly serialised I was expecting any error as response)

### If applicable, what are the logs from the server around the occurence of the problem?

https://gist.github.com/klarkc/046a6d2c731b979d556f338d1b479ffe

**Comment by KtorZ** [comment]
It's odd. Seems like it is the node closing the connection unexpectedly. This should in principle lead to an error response being sent from Ogmios' side; maybe it is being ignored by `cardano-transaction-lib`? 

Note that I am not able to reproduce this and I am simply getting a response:

```json
{"jsonrpc":"2.0","method":"evaluateTransaction","result":[],"id":"evaluateTransaction-ls2ebvv3"}
```

which seems to make sense since the transaction doesn't carry any scripts for execution? 

```json
❯ ogmios inspect transaction 84a[...]5f6 | jq
{
  "id": "a7da8e2c27fda72ec20d51ac10ea7265b22d6eb67c6b1d14defa5b2aaac95165",
  "spends": "inputs",
  "inputs": [
    {
      "transaction": {
        "id": "55ed5376ddaafcc1d498d96d7d45ebda05a4c63c3f9e0e99a345df0218db8cb1"
      },
      "index": 3
    }
  ],
  "outputs": [
    {
      "address": "addr_test1zpunlryvl7aqsxe22erzlsseej87v5kk5vutvtrmzdy8deufnjhc03swtq2c9fqgyph7dnzcu7nhntau294nwf4g9uhqq3ayq4",
      "value": {
        "ada": {
          "lovelace": 2000000
        }
      },
      "datumHash": "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec"
    },
    {
      "address": "addr_test1qz5r3f8p9q8nh78pgchh48tj3vlzwap8e5ydq5f9j3srenvfnjhc03swtq2c9fqgyph7dnzcu7nhntau294nwf4g9uhqajgvez",
      "value": {
        "ada": {
          "lovelace": 1246750000
        }
      }
    }
  ],
  "network": "testnet",
  "fee": {
    "ada": {
      "lovelace": 0
    }
  },
  "validityInterval": {},
  "signatories": [],
  "datums": {
    "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec": "d87980"
  }
}
```

**Comment by KtorZ** [comment]
Also note, I am here running with `cardano-node==8.7.3`; is it also the case for you?

**Comment by klarkc** [comment]
Hmm nice I was not aware of the `ogmios inspect` I'll try to understand what is happening in this transaction, but in the meantime this is [the example](https://github.com/sadMaxim/cardano-transaction-lib/blob/e461bce0d560d823fa064724e234826684c79a1e/examples/PlutusV2/AlwaysSucceeds.purs#L28-L38) I'm running.

Also yes, I'm running `cardano-node==8.7.3`

**Comment by klarkc** [comment]
So, these are my findings so far:

- The provided transaction (tx) is the only one being executed. I also double-checked the CBOR. The transaction is locking `2000000` lovelace in the `addr_test1z...yq4` script address.
- I'm unsure if the connection drop is caused by the client, cardano-node, or Ogmios.
- The `network` field caught my attention. It is set to `testnet`, but I'm running on the sanchonet. Cardano-transaction-lib is sending `0` for "testnet". Following [CDDL](https://github.com/IntersectMBO/cardano-ledger/blob/c158b4298d34cdef3340e600739422ca72a713cd/eras/conway/impl/cddl-files/conway.cddl#L578), I believe that's the expected value.
- `additionalUtxo` is empty, which I believe is probably a mistake. So, I'm trying to understand why I have an empty `additionalUtxo`. Is the client required to pass any script address there?

**Comment by KtorZ** [comment]
The `additionalUtxo` is meant to specify input UTxO that may either not yet be on-chain or may no longer be on-chain (should you want to replay a transaction). Under the hood, Ogmios tries to fetch the input UTxO that are part of the transaction and fallback to the `additionalUtxo` when they're missing. All inputs must be fully known for evaluation. 

The network id seems definitely wrong, and this should cause a mismatch error down the line. It is _plausible_ that this causes a de-serialization issue on the node side now instead of an application-level error; causing the node to simply drop the connection. If that's the case, I honestly think that's a mistake on the node's side (as deserializers shouldn't be mixed with app-logic like that...) but certainly we can do something about it within Ogmios to mitigate this ...

**Comment by klarkc** [comment]
More findings:

- The same CBOR format works with ogmios `v6.0.0`, cardano-node `8.1.1`, and cardano-transaction-lib `bee683f`; this is the latest working version with cardano-transaction-lib.
- In this functional version, the `additionalUtxo` field is also empty. I previously assumed there was a need to calculate execution costs to lock some value in the script address, but that was a mistake. It appears that `additionalUtxo` must indeed be empty.
- There are no connection drops in the operational version (at least on the client side), but surprisingly, the logs look very similar, including the cardano-node error. Thus, I believe the log is not providing useful information in this context.

Working log (relevant parts): https://gist.github.com/klarkc/f81a8b4d978d912aa7cf50ae146fe74b

**Comment by klarkc** [comment]
This is the CloseEvent received in the client (so yes, the server - ogmios closed the connection):

![2024-02-02-190516_625x302_scrot](https://github.com/CardanoSolutions/ogmios/assets/724959/ae1828e9-2fc8-443a-8985-ff47a0dd3cf7)

**Comment by klarkc** [comment]
This error code [1006](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5) indicates a connection issue. I'll investigate the server to understand what's happening, and I would appreciate it if you could guide me to the relevant function. Although I'm intrigued that you were unable to reproduce it. How did you test it?

**Comment by KtorZ** [comment]
I have simply submitted a payload with that a transaction to a running node through Ogmios connected to sanchonet. 

Note that Ogmios isn't guaranteed to work with 8.1.1; especially around the Conway era. There has been many breaking changes in the ledger that would cause a format discrepancy. So you should stick to 8.7.2 and higher.

**Comment by klarkc** [comment]
Here's the corrected version:

So, after many traces and elimination, I've found that this function is not terminating:

https://github.com/CardanoSolutions/ogmios/blob/0c16007a936648ee7e924bb305eaa5c24464acff/server/src/Ogmios/App/Protocol/TxSubmission.hs#L537

The `upgrade tx` is not returning; I don't know why. There is no error or log message regarding this function. I debugged it this way:

```hs
let
    utxo' = trace "up utxo" utxo `seq` upgrade utxo -- ok
    tx' = trace "up tx" tx `seq` upgrade tx -- upgrade tx never returns
-- returning Nothing forces a runtime error, so we can test if the upgrade is running
-- This fails: 
-- trace "utxo'" utxo' `seq` trace "tx'" tx' `seq` Nothing
-- This works:
trace "utxo'" utxo' `seq` Nothing
```

To eliminate a problem in `tx`, I also tested if `tx` is being evaluated correctly:

```hs
-- this correctly evaluates utxo and tx
trace "utxo" utxo `seq` trace "tx" `seq` Just (upgrade utxo, upgrade tx) 
```

There is an instance of `Upgrade` here:https://github.com/CardanoSolutions/ogmios/blob/0c16007a936648ee7e924bb305eaa5c24464acff/server/src/Ogmios/Data/EraTranslation.hs#L82-L95.

But it looks like Babbage -> Conway is not there. I tried to add a trace on the instance, but it has not been called.

I'm running out of options. I've been considering whether upgrading the node would make a difference, but it seems that the issue lies within the Ogmios Upgrade instance. Perhaps trying the same binary version of Ogmios that you're using could reveal any differences. Additionally, I might attempt to create an isolated test scenario to ensure the bug can be reproduced reliably.

**Comment by KtorZ** [comment]
> @klarkc But it looks like Babbage -> Conway is not there. 

That's because there's no `BabbageTx`; Babbage uses the same transaction format as Alonzo. 

Note also that this upgrade path is only called if you submit a Babbage transaction. If your transaction contains any Conway specifics, it'll be parsed as a Conway transaction from the start (since it'll fail to parse as a Babbage's one):

https://github.com/CardanoSolutions/ogmios/blob/0c16007a936648ee7e924bb305eaa5c24464acff/server/src/Ogmios/Data/Json/Query.hs#L1574-L1579

Are you able to share the culprit transaction so we can inspect it and I can try to reproduce?

**Comment by klarkc** [comment]
It seems I misinterpreted the trace; the `upgrade` instance is actually being called, and we're reaching something:

```diff
unsafeFromRight :: (HasCallStack, Show e) => Either e a -> a
-     unsafeFromRight = either (error . show) id
+     unsafeFromRight = either (\err -> error $ traceShowId $ show err) id
```

```
"DecoderErrorDeserialiseFailure \"witness\" (DeserialiseFailure 38 \"expected bytes\")"
```

I'm not sure why the runtime error is not being reported by the application 😅, but anyway, this is the result of `show (Alonzo.body tx)`:

```hs
TxBodyConstr BabbageTxBodyRaw {btbrSpendInputs = fromList [TxIn (TxId {unTxId = SafeHash "55ed5376ddaafcc1d498d96d7d45ebda05a4c63c3f9e0e99a345df0218db8cb1"}) (TxIx 4)], btbrCollateralInputs = fromList [], btbrReferenceInputs = fromList [], btbrOutputs = StrictSeq {fromStrict = fromList [Sized {sizedValue = (Addr Testnet (ScriptHashObj (ScriptHash "793f8c8cffba081b2a56462fc219cc8fe652d6a338b62c7b134876e7")) (StakeRefBase (KeyHashObj (KeyHash "899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e"))),MaryValue (Coin 2000000) (MultiAsset (fromList [])),DatumHash (SafeHash "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec"),SNothing), sizedSize = 99},Sized {sizedValue = (Addr Testnet (KeyHashObj (KeyHash "a838a4e1280f3bf8e1462f7a9d728b3e277427cd08d0512594603ccd")) (StakeRefBase (KeyHashObj (KeyHash "899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e"))),MaryValue (Coin 1246750000) (MultiAsset (fromList [])),NoDatum,SNothing), sizedSize = 65}]}, btbrCollateralReturn = SNothing, btbrTotalCollateral = SNothing, btbrCerts = StrictSeq {fromStrict = fromList []}, btbrWithdrawals = Withdrawals {unWithdrawals = fromList []}, btbrTxFee = Coin 0, btbrValidityInterval = ValidityInterval {invalidBefore = SNothing, invalidHereafter = SNothing}, btbrUpdate = SNothing, btbrReqSignerHashes = fromList [], btbrMint = MultiAsset (fromList []), btbrScriptIntegrityHash = SNothing, btbrAuxDataHash = SNothing, btbrTxNetworkId = SJust Testnet} (blake2b_256: SafeHash "bd0043887e1bcbc8d59beccb0cd394d0d7d862d207ad44d8091c3fd4ed21cb31")
```
Regarding the transaction, it is the same `84a...f5f6`, but it seems to happen with any transaction (Plutus V1 or V2). I did not test it with Conway features. It's very unlikely, but I one reason why you can't reproduce it would be due to differences in the build plan; I'm using [this flake](https://github.com/Fourierlabs/ogmios-nixos/blob/master/flake.nix) to build Ogmios. As it's not the same build you're using, that might result in some strange behavior.

**Comment by KtorZ** [comment]
Hey, are you able to figure out which version of cardano-ledger-alonzo, and cardano-ledger-conway get resolved by flakes here? The version of the ledger dictates which cbor decoders is being used underneath and there has been a lot of (breaking) changes in the ledger lately. 

Ideally, you should stick to what is specific in Ogmios' cabal.project; if that's not the case then I can't ensure compability.

**Comment by klarkc** [comment]
The freeze file: https://gist.github.com/klarkc/a625592a231c201a67d9df34d7d6b0de. I have also double-checked if the flags are being set in Nix logs, and yes, the log includes all the custom flags. However, I've discovered a custom `cabal.project.local` being added in the CI with some constraints that I was not aware of. Does this relate to the static build, and is there any specific reason to use a static build?

**Comment by KtorZ** [comment]
> I've discovered a custom cabal.project.local being added in the CI with some constraints that I was not aware of. Does this relate to the static build?

Yes indeed.

> Is there any specific reason to use a static build?

Yes, it's easier to ship around and put in containers. Dynamic linking has always been a source of pain for packaging developer tooling since everyone is using their own favorite package manager and developers are notorious for having custom half-working setups. Statically linked executable alleviate a lot of the pain.

---

@klarkc since I haven't been able to reproduce your issue, I still assume that is was a genuine compatibility issue between SanchoNet and Ogmios. SanchoNet is under heavy development, and the testnet is being restarted quite often with new node versions. Each time, the binary codecs break. Ogmios isn't yet compatible with the _current SanchoNet_ (although `master` is about to be in a few minutes once I merge #367). I'll be doing a full SanchoNet chain-sync as well as some extra other tests. I'd be thankful if you could provide some easy reproduction steps in addition since your original transaction is no longer actionable on the current SanchoNet.

**Comment by klarkc** [comment]
Even when building it with Cabal using the devx shell (not the static one), the issue persists:

```bash
nix develop github:input-output-hk/devx/b2073bd49eddcdb1e0ec2c9a12e6e42c345c66a#ghc96-iog --no-write-lock-file --refresh
```

(This revision is the same as being used in the CI for v6.0.2)

And by building it with the same GHC of the CI, (`github:input-output-hk/devx/b2073bd49eddcdb1e0ec2c9a12e6e42c345c66a#ghc96-static-minimal-iog`) the issue also persists. So it looks the build plan is not causing that :weary:

---

@KtorZ Ok, I'll try to upgrade Ogmios to see if the issue persists, and in that case, I'll build a new transaction where the issue happens in a reproducible environment. I'm also willing to attempt running it enabling Conway features to see what happens.

**Comment by klarkc** [comment]
Update, It happens on:

1. v6.0.3 with cardano-node v8.7.3
2. v6.1.0 with cardano-node v8.7.3 and v8.8.0

I'm still working on the reproduction repo and also PlutusV3.

**Comment by klarkc** [comment]
I've identified the issue; it was a corrupted local state on my end (on cardano-node). Recreating all volumes resolved the issue. 🤦‍♂️
